import { and, asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { animalCategories } from "../../../db/schema";
import { requireApiUser } from "../../api-auth";

const cabinId=1;
const slugify=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export async function GET(request:Request){try{const all=new URL(request.url).searchParams.get("all")==="1";if(all){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized}const rows=await getDb().select().from(animalCategories).where(all?eq(animalCategories.cabinId,cabinId):and(eq(animalCategories.cabinId,cabinId),eq(animalCategories.active,true))).orderBy(asc(animalCategories.sortOrder));return Response.json({categories:rows})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudieron cargar las categorías."},{status:500})}}
export async function POST(request:Request){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized;try{const body=await request.json() as {name?:string;catalogSection?:string;kind?:string};const name=String(body.name||"").trim();if(!name)return Response.json({error:"Ingresá un nombre."},{status:400});const catalogSection=body.catalogSection==="criollos"?"criollos" as const:"genetics" as const;const kind=body.kind==="coat"?"coat" as const:"category" as const;const db=getDb();const existing=await db.select({id:animalCategories.id}).from(animalCategories).where(and(eq(animalCategories.cabinId,cabinId),eq(animalCategories.catalogSection,catalogSection),eq(animalCategories.kind,kind)));const [category]=await db.insert(animalCategories).values({cabinId,name,slug:slugify(name),catalogSection,kind,sortOrder:existing.length,active:true}).returning();return Response.json({category},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo crear la opción."},{status:500})}}
export async function PATCH(request:Request){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized;try{const body=await request.json() as {id?:number;name?:string;active?:boolean;catalogSection?:string;kind?:string};const id=Number(body.id);const name=String(body.name||"").trim();if(!id||!name)return Response.json({error:"Opción inválida."},{status:400});const catalogSection=body.catalogSection==="criollos"?"criollos" as const:"genetics" as const;const kind=body.kind==="coat"?"coat" as const:"category" as const;const [category]=await getDb().update(animalCategories).set({name,slug:slugify(name),active:Boolean(body.active),catalogSection,kind}).where(and(eq(animalCategories.id,id),eq(animalCategories.cabinId,cabinId))).returning();return Response.json({category})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo actualizar la opción."},{status:500})}}
export async function DELETE(request:Request){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized;try{const id=Number(new URL(request.url).searchParams.get("id"));await getDb().delete(animalCategories).where(and(eq(animalCategories.id,id),eq(animalCategories.cabinId,cabinId)));return Response.json({deleted:id})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo eliminar la categoría."},{status:500})}}
