export const templateContent: Record<string,string> = {
  brand_name:"Cabaña Tupambaé",
  brand_tagline:"Hereford · Uruguay",
  seo_title:"Cabaña Tupambaé | Genética Hereford",
  seo_description:"Una propuesta de Cabaña Tupambaé dedicada a presentar su genética Hereford, reproductores y novedades.",
  seo_keywords:"Cabaña Tupambaé, Hereford, genética bovina, reproductores, Uruguay",
  home_hero_line_1:"Genética Hereford",
  home_hero_line_2:"con identidad propia.",
  home_hero_copy:"Una mirada a la selección, los reproductores y el trabajo de campo detrás de cada nueva generación.",
  home_intro_eyebrow:"La mirada de Tupambaé",
  home_intro_line_1:"Una raza, una visión.",
  home_intro_line_2:"El campo como origen.",
  home_intro_copy:"La genética se entiende mejor cuando se mira en el campo. Conocé la propuesta Hereford de Tupambaé y los animales que la representan.",
  cabana_eyebrow:"Cabaña Tupambaé · Uruguay",
  cabana_title_line_1:"Hereford con",
  cabana_title_line_2:"identidad propia.",
  cabana_lead:"Una propuesta centrada en la raza Hereford, el trabajo de campo y la selección de reproductores.",
  cabana_story_1:"Tupambaé es una cabaña uruguaya de Hereford. Esta presentación reúne su genética, sus animales y sus próximas novedades en un mismo lugar.",
  cabana_story_2:"La trayectoria del establecimiento, los criterios de selección y el sistema de producción se incorporarán con información provista por la cabaña.",
  cabana_year:"",
  story_values_eyebrow:"Ejes de la propuesta",
  story_value_1_title:"Raza Hereford",
  story_value_1_copy:"Una identidad reconocible que merece contarse con claridad y carácter.",
  story_value_2_title:"Selección",
  story_value_2_copy:"Cada ficha puede reunir pedigree, fotografías y datos para acompañar la elección.",
  story_value_3_title:"Producción",
  story_value_3_copy:"Del establecimiento al catálogo: animales y novedades en un mismo recorrido.",
  history_territory_title:"Territorio y ambiente",
  history_territory_copy:"",
  history_origins_title:"Orígenes de la cabaña",
  history_origins_copy:"",
  history_selection_title:"Selección genética",
  history_selection_copy:"",
  history_production_title:"Sistema productivo",
  history_production_copy:"",
  history_present_title:"Trabajo actual",
  history_present_copy:"",
  history_sales_title:"Producción y comercialización",
  history_sales_copy:"",
  establishment_name:"Cabaña Tupambaé",
  establishment_location:"Uruguay",
  genetics_line_1:"La fuerza de la raza.",
  genetics_line_2:"La mirada del campo.",
  genetics_hero_line_1:"Hereford, una raza.",
  genetics_hero_line_2:"Muchas posibilidades.",
  genetics_title:"Una selección Hereford para conocer de cerca",
  genetics_copy:"Explorá las fichas de reproductores, el pedigree y los datos disponibles. La información específica del programa se incorporará junto con el catálogo oficial de la cabaña.",
  genetics_cycle_title:"",
  genetics_cycle_copy:"",
  genetics_catalog_eyebrow:"Catálogo genético",
  genetics_catalog_title_line_1:"Nuestros",
  genetics_catalog_title_line_2:"animales.",
  genetics_catalog_copy:"Cada reproductor tendrá su espacio para mostrar imagen, origen y datos de interés. Las fichas se publicarán al recibir el catálogo de Tupambaé.",
  stat_1_value:"",
  stat_1_label:"",
  stat_2_value:"",
  stat_2_label:"",
  stat_3_value:"",
  stat_3_label:"",
  criollos_title_line_1:"Caballos Criollos",
  criollos_title_line_2:"de la cabaña.",
  criollos_lead:"",
  criollos_story_1:"",
  criollos_story_2:"",
  criollos_story_3:"",
  actualidad_intro:"Novedades, remates y encuentros de Cabaña Tupambaé. Próximamente se publicará contenido confirmado por la cabaña.",
  gallery_eyebrow:"Hereford · campo · Tupambaé",
  gallery_title_line_1:"Galería",
  gallery_title_line_2:"de la cabaña.",
  contact_line_1:"Hablemos de",
  contact_line_2:"Hereford.",
  contact_intro:"Para consultas sobre la cabaña o sus animales, escribinos por WhatsApp. Este contacto es provisorio para la propuesta.",
  contact_email:"",
  contact_phone:"+598 91 088 716",
  contact_whatsapp:"https://wa.me/59891088716",
  contact_location:"Uruguay",
  contact_map:"",
  social_instagram:"https://www.instagram.com/cabana_tupambae/",
  social_facebook:"",
  social_youtube:"",
  institutional_video:"",
  font_size_titles:"normal",
  font_size_body:"normal",
  typography_style:"clasica",
  color_palette:"tupambae",
  show_cabana:"true",
  show_genetics:"true",
  show_home_intro:"true",
  show_home_establishment:"true",
  show_home_genetics:"true",
  show_home_news_carousel:"false",
  show_home_gallery_carousel:"false",
  home_news_carousel_position:"after_auction",
  home_gallery_carousel_position:"after_auction",
  home_auction_position:"after_genetics",
  show_history_chapters:"false",
  show_story_values:"true",
  show_story_value_1:"true",
  show_story_value_2:"true",
  show_story_value_3:"true",
  show_cabana_establishment_image:"true",
  show_genetics_program:"true",
  show_genetics_hero:"true",
  show_genetics_intro:"true",
  show_genetics_stats:"false",
  show_genetics_results:"false",
  show_genetics_results_image:"true",
  show_genetics_catalog:"true",
  show_criollos:"false",
  show_criollos_image:"true",
  show_news:"true",
  show_gallery:"true",
  show_contact:"true",
  show_contact_image:"true",
  show_animal_watermark:"false",
  show_cabana_watermark:"false",
  custom_pages_json:"[]"
};

export const templateSiteImages = [
  ["seo-share","Vista previa al compartir","/tupambae-hero.jpg"],
  ["site-icon","Ícono del sitio","/tupambae-original-mark.png"],
  ["home-hero","Portada principal","/tupambae-hero.jpg"],
  ["establishment","El establecimiento","/tupambae-establishment.jpg"],
  ["genetics-hero","Programa genético","/tupambae-genetics.jpg"],
  ["genetics-cycle","Resultados productivos","/tupambae-genetics.jpg"],
  ["criollos-hero","Caballos Criollos","/tupambae-establishment.jpg"],
  ["contact","Página de contacto","/tupambae-establishment.jpg"],
  ["animal-gallery-secondary","Galería secundaria","/tupambae-establishment.jpg"],
  ["animal-gallery-tertiary","Galería terciaria","/tupambae-genetics.jpg"]
] as const;
