export const templateContent: Record<string,string> = {
  brand_name:"Nombre de la cabaña",
  brand_tagline:"Genética, trabajo y tradición",
  seo_title:"",
  seo_description:"",
  seo_keywords:"genética bovina, cabaña ganadera, reproductores",
  home_hero_line_1:"Una historia de campo",
  home_hero_line_2:"con identidad propia.",
  home_hero_copy:"Completá la identidad, la historia y la propuesta genética desde el administrador de esta web.",
  home_intro_eyebrow:"Nuestra cabaña",
  home_intro_line_1:"Selección con propósito.",
  home_intro_line_2:"Resultados consistentes.",
  home_intro_copy:"Contá aquí la filosofía de trabajo, los objetivos productivos y aquello que distingue a la cabaña.",
  cabana_eyebrow:"Historia de la cabaña",
  cabana_title_line_1:"Tradición, trabajo",
  cabana_title_line_2:"y evolución.",
  cabana_lead:"Presentá el establecimiento, su origen y el camino recorrido por la familia o el equipo.",
  cabana_story_1:"Este contenido se reemplaza desde /admin con la historia real de cada cabaña.",
  cabana_story_2:"También se pueden describir la filosofía, el sistema productivo y los criterios de selección.",
  cabana_year:"",
  story_values_eyebrow:"Nuestra manera de hacer",
  story_value_1_title:"Datos + campo",
  story_value_1_copy:"Información objetiva acompañada por observación permanente.",
  story_value_2_title:"Adaptación",
  story_value_2_copy:"Animales funcionales en condiciones reales de producción.",
  story_value_3_title:"Consistencia",
  story_value_3_copy:"Una dirección genética sostenida generación tras generación.",
  history_territory_title:"Territorio y ambiente",
  history_territory_copy:"",
  history_origins_title:"Orígenes de la cabaña",
  history_origins_copy:"",
  history_selection_title:"Selección genética",
  history_selection_copy:"",
  history_production_title:"Sistema productivo",
  history_production_copy:"",
  history_present_title:"Trabajo actual",
  history_present_copy:"",
  history_sales_title:"Producción y comercialización",
  history_sales_copy:"",
  establishment_name:"Nombre del establecimiento",
  establishment_location:"Localidad · Departamento · País",
  genetics_line_1:"Genética funcional.",
  genetics_line_2:"Datos y campo.",
  genetics_title:"Un programa genético orientado a resultados",
  genetics_copy:"Describí los objetivos, las herramientas de evaluación y las características buscadas en cada generación.",
  genetics_cycle_title:"Resultados productivos",
  genetics_cycle_copy:"",
  genetics_catalog_eyebrow:"Catálogo genético",
  genetics_catalog_title_line_1:"Nuestros",
  genetics_catalog_title_line_2:"animales.",
  genetics_catalog_copy:"Las fichas publicadas por la cabaña aparecen automáticamente en este catálogo.",
  stat_1_value:"",
  stat_1_label:"",
  stat_2_value:"",
  stat_2_label:"",
  stat_3_value:"",
  stat_3_label:"",
  criollos_title_line_1:"Caballos Criollos",
  criollos_title_line_2:"de la cabaña.",
  criollos_lead:"",
  criollos_story_1:"",
  criollos_story_2:"",
  criollos_story_3:"",
  actualidad_intro:"",
  gallery_eyebrow:"El campo, los animales y nuestra gente",
  gallery_title_line_1:"Galería",
  gallery_title_line_2:"de la cabaña.",
  contact_line_1:"Conversemos",
  contact_line_2:"sobre genética.",
  contact_intro:"Completá los datos de contacto, redes sociales y ubicación desde el administrador.",
  contact_email:"",
  contact_phone:"",
  contact_whatsapp:"",
  contact_location:"",
  contact_map:"",
  social_instagram:"",
  social_facebook:"",
  social_youtube:"",
  institutional_video:"",
  font_size_titles:"normal",
  font_size_body:"normal",
  color_palette:"tierra",
  show_cabana:"true",
  show_genetics:"true",
  show_home_intro:"true",
  show_home_establishment:"true",
  show_home_genetics:"true",
  show_home_news_carousel:"false",
  show_home_gallery_carousel:"false",
  home_news_carousel_position:"after_auction",
  home_gallery_carousel_position:"after_auction",
  home_auction_position:"after_genetics",
  show_history_chapters:"false",
  show_story_values:"true",
  show_story_value_1:"true",
  show_story_value_2:"true",
  show_story_value_3:"true",
  show_cabana_establishment_image:"true",
  show_genetics_program:"true",
  show_genetics_hero:"true",
  show_genetics_intro:"true",
  show_genetics_stats:"true",
  show_genetics_results:"true",
  show_genetics_results_image:"true",
  show_genetics_catalog:"true",
  show_criollos:"false",
  show_criollos_image:"true",
  show_news:"true",
  show_gallery:"true",
  show_contact:"true",
  show_contact_image:"true",
  show_animal_watermark:"false",
  show_cabana_watermark:"false",
  custom_pages_json:"[]"
};

export const templateSiteImages = [
  ["seo-share","Vista previa al compartir","/hero-cattle.jpg"],
  ["site-icon","Ícono del sitio","/favicon.svg"],
  ["home-hero","Portada principal","/hero-cattle.jpg"],
  ["establishment","El establecimiento","/ranch.jpg"],
  ["genetics-hero","Programa genético","/cattle-field.jpg"],
  ["genetics-cycle","Resultados productivos","/animal-black.jpg"],
  ["criollos-hero","Caballos Criollos","/ranch.jpg"],
  ["contact","Página de contacto","/cattle-field.jpg"],
  ["animal-gallery-secondary","Galería secundaria","/ranch.jpg"],
  ["animal-gallery-tertiary","Galería terciaria","/cattle-field.jpg"]
] as const;
