import { and, asc, eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { galleryCategories } from "../../../db/schema";
import { requireApiUser } from "../../api-auth";

const cabinId=1;
const slugify=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export async function GET(request:Request){try{const all=new URL(request.url).searchParams.get("all")==="1";if(all){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized}const rows=await getDb().select().from(galleryCategories).where(all?eq(galleryCategories.cabinId,cabinId):and(eq(galleryCategories.cabinId,cabinId),eq(galleryCategories.active,true))).orderBy(asc(galleryCategories.sortOrder));return Response.json({categories:rows})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudieron cargar las categorías de galería."},{status:500})}}
export async function POST(request:Request){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized;try{const body=await request.json() as {name?:string};const name=String(body.name||"").trim();if(!name)return Response.json({error:"Ingresá un nombre."},{status:400});const db=getDb();const existing=await db.select({id:galleryCategories.id}).from(galleryCategories).where(eq(galleryCategories.cabinId,cabinId));const [category]=await db.insert(galleryCategories).values({cabinId,name,slug:slugify(name),sortOrder:existing.length,active:true}).returning();return Response.json({category},{status:201})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo crear la categoría."},{status:500})}}
export async function PATCH(request:Request){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized;try{const body=await request.json() as {id?:number;name?:string;active?:boolean};const id=Number(body.id);const name=String(body.name||"").trim();if(!id||!name)return Response.json({error:"Categoría inválida."},{status:400});const [category]=await getDb().update(galleryCategories).set({name,slug:slugify(name),active:Boolean(body.active)}).where(and(eq(galleryCategories.id,id),eq(galleryCategories.cabinId,cabinId))).returning();return Response.json({category})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo actualizar la categoría."},{status:500})}}
export async function DELETE(request:Request){const unauthorized=await requireApiUser();if(unauthorized)return unauthorized;try{const id=Number(new URL(request.url).searchParams.get("id"));await getDb().delete(galleryCategories).where(and(eq(galleryCategories.id,id),eq(galleryCategories.cabinId,cabinId)));return Response.json({deleted:id})}catch(error){return Response.json({error:error instanceof Error?error.message:"No se pudo eliminar la categoría."},{status:500})}}
